import React from "react";
import { GeneratedReport } from "../../types/analytics.types";
import { reportService } from "../../services/reportService";
import { X, Download, Printer, Copy, FileText } from "lucide-react";

interface Props {
  report: GeneratedReport | null;
  onClose: () => void;
}

export const ReportPreviewModal: React.FC<Props> = ({ report, onClose }) => {
  if (!report) return null;

  const handleDownloadCsv = () => {
    reportService.downloadReportCsv(report.id, `${report.id}-${report.station.code}.csv`);
  };

  const handlePrint = () => {
    reportService.openReportPrintView(report.id);
  };

  const handleCopyJson = () => {
    navigator.clipboard.writeText(JSON.stringify(report, null, 2));
    alert("Report JSON copied to clipboard");
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm animate-in fade-in">
      <div className="bg-slate-900 border border-slate-800 rounded-2xl w-full max-w-4xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden">
        {/* Modal Header */}
        <div className="px-6 py-4 border-b border-slate-800 flex items-center justify-between bg-slate-950/60">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-sky-500/15 text-sky-400 flex items-center justify-center">
              <FileText className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-white">{report.title}</h3>
              <div className="text-[10px] text-slate-400">
                ID: {report.id} • Station: {report.station.name} ({report.station.code})
              </div>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handleDownloadCsv}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg text-xs font-medium transition-all"
              title="Download CSV"
            >
              <Download className="w-3.5 h-3.5 text-sky-400" />
              <span>CSV</span>
            </button>

            <button
              type="button"
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-sky-600 hover:bg-sky-500 text-white rounded-lg text-xs font-medium transition-all shadow-sm"
              title="Print / Export PDF"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / PDF</span>
            </button>

            <button
              type="button"
              onClick={handleCopyJson}
              className="p-1.5 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-lg transition-all"
              title="Copy JSON"
            >
              <Copy className="w-4 h-4" />
            </button>

            <button
              type="button"
              onClick={onClose}
              className="p-1.5 bg-slate-800/80 hover:bg-slate-700 text-slate-400 hover:text-white rounded-lg transition-all ml-1"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Modal Scrollable Body */}
        <div className="p-6 overflow-y-auto space-y-6 text-xs text-slate-300">
          {/* Metadata Banner */}
          <div className="bg-slate-950/80 border border-slate-800 rounded-xl p-4 grid grid-cols-2 sm:grid-cols-4 gap-3">
            <div>
              <span className="text-[10px] uppercase font-bold text-slate-500">Report Period</span>
              <div className="text-slate-200 font-medium mt-0.5">{report.period.label}</div>
            </div>
            <div>
              <span className="text-[10px] uppercase font-bold text-slate-500">Generated At</span>
              <div className="text-slate-200 font-medium mt-0.5">
                {new Date(report.generatedAt).toLocaleString()}
              </div>
            </div>
            <div>
              <span className="text-[10px] uppercase font-bold text-slate-500">Generated By</span>
              <div className="text-slate-200 font-medium mt-0.5">{report.generatedBy}</div>
            </div>
            <div>
              <span className="text-[10px] uppercase font-bold text-slate-500">Data Coverage</span>
              <div className="text-emerald-400 font-medium mt-0.5">
                {report.dataQuality.rating} ({report.dataQuality.coveragePercent}%)
              </div>
            </div>
          </div>

          {/* Executive Operations Summary */}
          <div className="bg-slate-950/50 border-l-4 border-sky-500 p-4 rounded-r-xl">
            <h4 className="text-xs font-bold text-white uppercase tracking-wider mb-1.5">
              Executive Operations Summary
            </h4>
            <p className="text-slate-300 leading-relaxed">{report.executiveSummary}</p>
          </div>

          {/* Key Metric KPIs */}
          <div>
            <h4 className="text-xs font-bold text-white uppercase tracking-wider mb-3">
              Key Operational Indicators
            </h4>
            <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3">
              {report.keyMetrics.map((kpi) => (
                <div key={kpi.key} className="bg-slate-950/80 border border-slate-800/80 rounded-lg p-3">
                  <div className="text-[10px] text-slate-400 truncate">{kpi.label}</div>
                  <div className="text-base font-bold text-white mt-1">
                    {kpi.currentValue ?? "N/A"}{" "}
                    <span className="text-[10px] font-normal text-slate-400">{kpi.unit}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Tables Section */}
          <div className="space-y-6">
            {report.tables.map((tbl, i) => (
              <div key={i} className="bg-slate-950/80 border border-slate-800 rounded-xl p-4 shadow">
                <h4 className="text-xs font-bold text-white uppercase tracking-wider mb-3">
                  {tbl.name}
                </h4>
                <div className="overflow-x-auto">
                  <table className="w-full text-left text-xs">
                    <thead>
                      <tr className="border-b border-slate-800 text-slate-400 font-semibold">
                        {tbl.columns.map((c, idx) => (
                          <th key={idx} className="pb-2 px-2.5">
                            {c}
                          </th>
                        ))}
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-800/60 text-slate-200">
                      {tbl.rows.map((row, rIdx) => (
                        <tr key={rIdx} className="hover:bg-slate-900/50">
                          {row.map((cell, cIdx) => (
                            <td key={cIdx} className="py-2 px-2.5">
                              {cell !== null && cell !== undefined ? String(cell) : "—"}
                            </td>
                          ))}
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            ))}
          </div>

          {/* Operational Observations */}
          <div>
            <h4 className="text-xs font-bold text-white uppercase tracking-wider mb-2">
              Operational Observations
            </h4>
            <ul className="space-y-1.5">
              {report.observations.map((obs, idx) => (
                <li key={idx} className="flex items-start gap-2 bg-slate-950/40 p-2.5 rounded border border-slate-800/80">
                  <span className="text-sky-400 font-bold">•</span>
                  <span>{obs}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Governance Notes */}
          <div className="pt-4 border-t border-slate-800 text-[11px] text-slate-500 space-y-1">
            <div className="font-semibold text-slate-400 uppercase tracking-wider">Governance Disclaimers</div>
            {report.notes.map((n, idx) => (
              <div key={idx}>• {n}</div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};
